version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest # Specify the Node.js version
    commands:
      - echo Installing source NPM dependencies...
      - npm install --verbose #to get more detailed error messages

  build:
    commands:
      - echo Build started on `date`
      - npm run build

artifacts:
  files:
    - '**/*'
